"""add secret to endpoints

Revision ID: 49e7f68b0f2a
Revises: b011a4873f5d
Create Date: 2026-03-16 01:55:54.886501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49e7f68b0f2a'
down_revision: Union[str, Sequence[str], None] = 'b011a4873f5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoints', sa.Column('secret', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('endpoints', 'secret')
    # ### end Alembic commands ###
