"""add cascade delete on endpoints

Revision ID: 60679f129bc2
Revises: 6b2a2d6be430
Create Date: 2026-03-15 20:55:50.136522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60679f129bc2'
down_revision: Union[str, Sequence[str], None] = '6b2a2d6be430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('captured_requests_endpoint_id_fkey'), 'captured_requests', type_='foreignkey')
    op.create_foreign_key(None, 'captured_requests', 'endpoints', ['endpoint_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'captured_requests', type_='foreignkey')
    op.create_foreign_key(op.f('captured_requests_endpoint_id_fkey'), 'captured_requests', 'endpoints', ['endpoint_id'], ['id'])
    # ### end Alembic commands ###
