"""add session_id to endpoints

Revision ID: b011a4873f5d
Revises: ed88fffb3b28
Create Date: 2026-03-15 22:02:04.142846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b011a4873f5d'
down_revision: Union[str, Sequence[str], None] = 'ed88fffb3b28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoints', sa.Column('session_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_endpoints_session_id'), 'endpoints', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_endpoints_session_id'), table_name='endpoints')
    op.drop_column('endpoints', 'session_id')
    # ### end Alembic commands ###
