"""cascade delete on delivery attempts

Revision ID: ed88fffb3b28
Revises: 60679f129bc2
Create Date: 2026-03-15 21:27:38.085957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed88fffb3b28'
down_revision: Union[str, Sequence[str], None] = '60679f129bc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('delivery_attempts_request_id_fkey'), 'delivery_attempts', type_='foreignkey')
    op.create_foreign_key(None, 'delivery_attempts', 'captured_requests', ['request_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'delivery_attempts', type_='foreignkey')
    op.create_foreign_key(op.f('delivery_attempts_request_id_fkey'), 'delivery_attempts', 'captured_requests', ['request_id'], ['id'])
    # ### end Alembic commands ###
